### ISSUE TITLE
Can not find the body  in the RVIZ

### ISSUE THREAD

**Issue by andiconda** [ravijo/rviz_skeleton_visualization#1]
1. roslaunch kinect_anywhere kinect_anywhere.launch color:=true body:=true pointcloud:=true kinect_frame:=base (It can work)
2. roslaunch rviz_skeleton_visualization visualization.launch
(It can work but in the Rviz the 'bodies' can not be added)

**Comment by ravijo** [comment]
Hi,

At present, `visualization.launch` in `rviz_skeleton_visualization` is using recorded data. Hence the ros package `rviz_skeleton_visualization` has nothing to do with `kinect_anywhere` package.

I checked `roslaunch rviz_skeleton_visualization visualization.launch` command and found it working. I suspect only one error in your case. Please make sure the `visualization.py` is executable by running following command:
```
chmod +x ~/ros_ws/src/rviz_skeleton_visualization/scripts/visualization.py
```
Please note that my ROS workspace is located inside $HOME. You may have to change the above command accordingly.

Additional Information
---
For real-time visualization of a skeleton, you need to modify [visualization.py](https://github.com/ravijo/rviz_skeleton_visualization/blob/master/scripts/visualization.py#L66) and provide `skeleton_joints`. If you need I can push this code to the repository. Let me know.

Cheers!

**Comment by andiconda** [comment]
I can get all other data and it can work well and the skeleton with the recorded data. How make it run with realtime data~ Thks

**Comment by ravijo** [comment]
I pushed the code for real-time visualization. Please check it out. Don't forget to install [kinect_anywhere](https://github.com/ravijo/kinect_anywhere) as it is used to obtain Kinect data.

Cheers!

**Comment by andiconda** [comment]
Thank you
